# Generated by Django 4.1.7 on 2023-10-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersaddinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/avatars/'),
        ),
    ]
