# Generated by Django 4.1.7 on 2023-11-09 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0002_alter_table23_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table23',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table23', to=settings.AUTH_USER_MODEL),
        ),
    ]
